apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: automate-custom-flask
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-image-bot
        email: flux-image-bot@example.com
    push:
      branch: main
  update:
    strategy: Regexp
      regexp:
        # file path relative to repo root (folder containing the files you want updated)
        path: "k8s/clusters/my-cluster/apps/flask-redis-app"
        # regexp to find the image line and replace with the new tag
        pattern: '(^\s*tag:\s*)v[0-9A-Za-z\.\-]+(\s*$)'
        replace: '${1}{{ .Tag }}${2}'