apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: automate-custom-flask
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flask-redis-app-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-image-bot
        email: flux-image-bot@example.com
    push:
      branch: main
  update:
    strategy: Setters
    path: k8s/flask-redis-app